name: defaults
on:
  push:
    branches:
      - main
jobs:
  job1:
    name: a
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # working-directory: ./scripts
    steps:
      - run: |
          sleep 10
          echo "abc"